import numpy as np
import matplotlib.pyplot as plt

class DeformableGradientToroid:
    def __init__(self, center, radius, vorticity_vec, num_nodes=24, minor_radius=0.15, pulse_amp=0.3, freq=15.0, phase=0.0, c=1.0):
        """
        A pristine, first-principles toroidal core where motion emerges entirely 
        from node-level boundary migration along the localized kinetic energy gradient.
        """
        self.N = num_nodes
        self.r_m = float(minor_radius)
        self.c = float(c)
        self.pulse_amp = float(pulse_amp)
        self.freq = float(freq)
        self.phase = float(phase)
        
        center = np.array(center, dtype=np.float64)
        omega = np.array(vorticity_vec, dtype=np.float64)
        omega_mag = np.linalg.norm(omega)
        normal = omega / omega_mag if omega_mag > 1e-12 else np.array([0.0, 0.0, 1.0])
        
        self.circulation = omega_mag * np.pi * (self.r_m ** 2)
        
        # Build initial coordinate ring
        arb = np.array([0.0, 0.0, 1.0]) if abs(normal[2]) < 0.9 else np.array([0.0, 1.0, 0.0])
        u = np.cross(normal, arb); u /= np.linalg.norm(u)
        v = np.cross(normal, u)
        
        theta = np.linspace(0, 2 * np.pi, self.N, endpoint=False)
        self.nodes = np.zeros((self.N, 3), dtype=np.float64)
        for i in range(self.N):
            self.nodes[i] = center + radius * (np.cos(theta[i]) * u + np.sin(theta[i]) * v)
            
        self.target_spacing = 2 * radius * np.sin(np.pi / self.N)

    def project_field(self, target_point, t):
        """
        Projects the total velocity vector field (DC circulation + AC wave breathing)
        generated by this deformed loop layout.
        """
        x = np.array(target_point, dtype=np.float64)
        v_total = np.zeros(3, dtype=np.float64)
        
        for i in range(self.N):
            node_curr = self.nodes[i]
            node_next = self.nodes[(i + 1) % self.N]
            
            delta_s = node_next - node_curr
            midpoint = (node_curr + node_next) * 0.5
            r_vec = x - midpoint
            r_mag = np.linalg.norm(r_vec)
            
            if r_mag < 1e-10:
                continue
                
            # 1. DC Vortex Circulation
            denominator_dc = (r_mag**2 + (self.r_m ** 2)) ** 1.5
            v_dc = (self.circulation / (4 * np.pi)) * (np.cross(delta_s, r_vec) / denominator_dc)
            
            # 2. AC Radial Breathing Wave
            time_of_flight_lag = r_mag / self.c
            wave_term = np.cos(self.freq * (t - time_of_flight_lag) + self.phase)
            v_ac = self.pulse_amp * wave_term * (r_vec / r_mag)
            
            v_total += v_dc + v_ac
            
        return v_total

    def step_kinematics(self, external_field_evaluator, t, dt, suction_stiffness=0.25, tension_stiffness=5.0):
        """
        Advects each node independently along the spatial gradient of the external
        kinetic energy density field, regulated by structural loop tension.
        """
        new_nodes = np.zeros_like(self.nodes)
        eps = 0.03  # Spatial probing distance
        
        for i in range(self.N):
            curr_node = self.nodes[i]
            
            # --- 1. PROBE LOCAL GRADIENT OF EXTERNAL KINETIC ENERGY (nabla v^2) ---
            grad_v_sq = np.zeros(3)
            for axis in range(3):
                nudge = np.zeros(3)
                nudge[axis] = eps
                
                # Sample field speed slightly forward and backward along this axis
                v_plus = np.linalg.norm(external_field_evaluator(curr_node + nudge, t))
                v_minus = np.linalg.norm(external_field_evaluator(curr_node - nudge, t))
                
                # Center-difference slope formula
                grad_v_sq[axis] = (v_plus**2 - v_minus**2) / (2 * eps)
            
            # Kinetic suction pulls nodes directly toward the highest field velocity
            v_suction = grad_v_sq * suction_stiffness
            
            # --- 2. CALCULATE INTERNAL COHESIVE COALESCENCE SKIN TENSION ---
            prev_node = self.nodes[(i - 1) % self.N]
            next_node = self.nodes[(i + 1) % self.N]
            
            vec_prev = prev_node - curr_node
            vec_next = next_node - curr_node
            
            d_prev = np.linalg.norm(vec_prev)
            d_next = np.linalg.norm(vec_next)
            
            f_prev = tension_stiffness * (d_prev - self.target_spacing) * (vec_prev / d_prev)
            f_next = tension_stiffness * (d_next - self.target_spacing) * (vec_next / d_next)
            v_internal = f_prev + f_next
            
            # --- 3. EXECUTE UNYIELDING SATURATION CEILING ---
            v_node_raw = v_suction + v_internal
            v_node_mag = np.linalg.norm(v_node_raw)
            if v_node_mag > self.c:
                v_node_raw = self.c * (v_node_raw / v_node_mag)
                
            new_nodes[i] = curr_node + v_node_raw * dt
            
        self.nodes = new_nodes

    def get_center_of_mass(self):
        return np.mean(self.nodes, axis=0)


# --- TIMELINE LIVE RUN EXECUTION ---
if __name__ == "__main__":
    # Core A: Stationary high-intensity proton anchor loop at origin
    core_A = DeformableGradientToroid(center=[0.0, 0.0, 0.0], radius=0.6, vorticity_vec=[0.0, 0.0, 35.0], phase=0.0)
    
    # Core B: Mobile loop offset along X-axis at X = 2.4
    core_B = DeformableGradientToroid(center=[2.4, 0.0, 0.0], radius=0.5, vorticity_vec=[0.0, 0.0, 25.0], phase=np.pi)
    
    steps = 160
    dt = 0.025
    
    com_A_track, com_B_track = [], []
    initial_nodes_B = core_B.nodes.copy()
    
    print("=== EXECUTING Lagrangian GRADIENT ENGINE LOOP ===")
    for step in range(steps):
        t = step * dt
        com_A_track.append(core_A.get_center_of_mass())
        com_B_track.append(core_B.get_center_of_mass())
        
        # Symmetrically pass dynamic field evaluators using clean lambda routing
        evaluator_for_A = lambda pos, time: core_B.project_field(pos, time)
        evaluator_for_B = lambda pos, time: core_A.project_field(pos, time)
        
        # Advance both node arrays simultaneously
        core_A.step_kinematics(evaluator_for_A, t, dt)
        core_B.step_kinematics(evaluator_for_B, t, dt)
        
    com_A_track = np.array(com_A_track)
    com_B_track = np.array(com_B_track)
    
    print("Simulation completed. Rendering node topology profile...")
    
    # --- MATPLOTLIB VISUALIZATION ---
    plt.figure(figsize=(12, 6), facecolor='#111116')
    ax = plt.gca()
    ax.set_facecolor('#111116')
    
    # Plot baseline reference rings
    plt.plot(core_A.nodes[:, 0], core_A.nodes[:, 1], color='magenta', linestyle='-', linewidth=1.5, alpha=0.6, label='Anchor Core A')
    plt.plot(initial_nodes_B[:, 0], initial_nodes_B[:, 1], color='cyan', linestyle='--', alpha=0.3, label='Core B Initial State')
    
    # Plot final node positions and elongated boundary shape
    plt.plot(core_B.nodes[:, 0], core_B.nodes[:, 1], color='cyan', linewidth=2.5, label='Core B Final Deformed Shape')
    plt.scatter(core_B.nodes[:, 0], core_B.nodes[:, 1], color='cyan', s=25, zorder=3)
    
    # Plot the true statistical Center of Mass path
    plt.plot(com_B_track[:, 0], com_B_track[:, 1], color='yellow', linestyle=':', linewidth=2.5, label='Emergent COM Suction Path')
    plt.scatter(com_B_track[0, 0], com_B_track[0, 1], color='yellow', marker='*', s=150, label='COM Start Position', zorder=5)
    plt.scatter(com_B_track[-1, 0], com_B_track[-1, 1], color='lime', marker='D', s=60, label='COM Final Position', zorder=5)
    
    plt.title("TIR Node-Level Engine: Emergent Attraction via Localized Energy Gradient (nabla v^2)", color='white', fontsize=12, pad=10)
    plt.xlabel("Substrate Horizon: X", color='white')
    plt.ylabel("Substrate Horizon: Y", color='white')
    plt.grid(color='#222233', linestyle=':', linewidth=0.5)
    ax.tick_params(colors='white')
    ax.set_aspect('equal')
    plt.legend(facecolor='#1c1c24', edgecolor='none', labelcolor='white')
    plt.xlim([-1.0, 3.2])
    plt.ylim([-1.5, 1.5])
    plt.show()