import numpy as np
import matplotlib.pyplot as plt

class DeformableToroid:
    def __init__(self, center, radius, vorticity_vec, num_nodes=24, minor_radius=0.15, pulse_amp=0.3, freq=15.0, phase=0.0, c=1.0):
        """
        A first-principles toroidal core defined strictly by an array of independently
        floating Lagrangian nodes. Motion emerges entirely from boundary migration.
        """
        self.N = num_nodes
        self.r_m = float(minor_radius)
        self.c = float(c)
        self.pulse_amp = float(pulse_amp)
        self.freq = float(freq)
        self.phase = float(phase)
        
        center = np.array(center, dtype=np.float64)
        omega = np.array(vorticity_vec, dtype=np.float64)
        omega_mag = np.linalg.norm(omega)
        normal = omega / omega_mag if omega_mag > 1e-12 else np.array([0.0, 0.0, 1.0])
        
        self.circulation = omega_mag * np.pi * (self.r_m ** 2)
        
        # Build initial planar circle basis vectors
        arb = np.array([0.0, 0.0, 1.0]) if abs(normal[2]) < 0.9 else np.array([0.0, 1.0, 0.0])
        u = np.cross(normal, arb); u /= np.linalg.norm(u)
        v = np.cross(normal, u)
        
        theta = np.linspace(0, 2 * np.pi, self.N, endpoint=False)
        self.nodes = np.zeros((self.N, 3), dtype=np.float64)
        for i in range(self.N):
            self.nodes[i] = center + radius * (np.cos(theta[i]) * u + np.sin(theta[i]) * v)
            
        self.target_spacing = 2 * radius * np.sin(np.pi / self.N)

    def project_field(self, target_point, t):
        """
        Projects the total velocity vector field (DC circulation + AC wave breathing)
        generated by this deformed loop into any target spatial coordinate.
        """
        x = np.array(target_point, dtype=np.float64)
        v_total = np.zeros(3, dtype=np.float64)
        
        for i in range(self.N):
            node_curr = self.nodes[i]
            node_next = self.nodes[(i + 1) % self.N]
            
            delta_s = node_next - node_curr
            midpoint = (node_curr + node_next) * 0.5
            r_vec = x - midpoint
            r_mag = np.linalg.norm(r_vec)
            
            if r_mag < 1e-10:
                continue
                
            # 1. DC Whirling Circulation (Biot-Savart regularized by minor radius)
            denominator_dc = (r_mag**2 + (self.r_m ** 2)) ** 1.5
            v_dc = (self.circulation / (4 * np.pi)) * (np.cross(delta_s, r_vec) / denominator_dc)
            
            # 2. AC Retarded Phase Radial Breathing (Electric/Wave chassis)
            time_of_flight_lag = r_mag / self.c
            wave_term = np.cos(self.freq * (t - time_of_flight_lag) + self.phase)
            v_ac = self.pulse_amp * wave_term * (r_vec / r_mag)
            
            v_total += v_dc + v_ac
            
        return v_total

    def step_kinematics(self, external_field_at_node, dt, tension_stiffness=4.0):
        """
        Updates each node independently based on local background substrate fields
        and nearest-neighbor internal loop continuity constraints.
        """
        new_nodes = np.zeros_like(self.nodes)
        
        for i in range(self.N):
            curr_node = self.nodes[i]
            v_ext = external_field_at_node[i]
            
            # Internal Cohesive Tension (Restoring forces maintaining the loop skin)
            prev_node = self.nodes[(i - 1) % self.N]
            next_node = self.nodes[(i + 1) % self.N]
            
            vec_prev = prev_node - curr_node
            vec_next = next_node - curr_node
            
            d_prev = np.linalg.norm(vec_prev)
            d_next = np.linalg.norm(vec_next)
            
            f_prev = tension_stiffness * (d_prev - self.target_spacing) * (vec_prev / d_prev)
            f_next = tension_stiffness * (d_next - self.target_spacing) * (vec_next / d_next)
            v_internal = f_prev + f_next
            
            # Combine fields
            v_node_raw = v_ext + v_internal
            
            # CRITICAL UNYIELDING CEILING CONSTRAINT (v <= c)
            v_node_mag = np.linalg.norm(v_node_raw)
            if v_node_mag > self.c:
                v_node_raw = self.c * (v_node_raw / v_node_mag)
                
            new_nodes[i] = curr_node + v_node_raw * dt
            
        self.nodes = new_nodes

    def get_center_of_mass(self):
        """Calculates the statistical center of mass of the deformed loop state."""
        return np.mean(self.nodes, axis=0)


# --- EXECUTION SANDBOX TIMELINE ---
if __name__ == "__main__":
    # Core A: Heavy vertical spin anchor loop centered at the origin
    core_A = DeformableToroid(center=[0.0, 0.0, 0.0], radius=0.6, vorticity_vec=[0.0, 0.0, 40.0], phase=0.0)
    
    # Core B: Mobile loop offset along X-axis, initialized out-of-phase (phase=pi)
    # core_B = DeformableToroid(center=[2.0, 0.0, 0.0], radius=0.5, vorticity_vec=[0.0, 0.0, 30.0], phase=np.pi)
    
    # Flip Core B's spin to negative Z (Opposite Spin / Opposite Charge)
    # Now the left side of B will spin Up (+Y), matching the right side of A!
    core_B = DeformableToroid(
        center=[2.0, 0.0, 0.0], 
        radius=0.5, 
        vorticity_vec=[0.0, 0.0, -30.0], # Inverted spin axis
        phase=np.pi
    )
    
    steps = 150
    dt = 0.02
    
    # Tracking logs
    com_A_track, com_B_track = [], []
    initial_nodes_B = core_B.nodes.copy()
    
    print("=== EXECUTING LAGRANGIAN NODE-FLEXING INTERACTION ===")
    for step in range(steps):
        t = step * dt
        com_A_track.append(core_A.get_center_of_mass())
        com_B_track.append(core_B.get_center_of_mass())
        
        # Cross-sample the velocity vector fields at the exact node coordinates
        v_ext_on_A = np.array([core_B.project_field(n, t) for n in core_A.nodes])
        v_ext_on_B = np.array([core_A.project_field(n, t) for n in core_B.nodes])
        
        # Simultaneous positional advection execution step
        core_A.step_kinematics(v_ext_on_A, dt)
        core_B.step_kinematics(v_ext_on_B, dt)
        
    com_A_track = np.array(com_A_track)
    com_B_track = np.array(com_B_track)
    
    print("Simulation complete. Preparing relational physics render...")
    
    # --- RENDERING ENGINE ---
    plt.figure(figsize=(12, 6), facecolor='#111116')
    ax = plt.gca()
    ax.set_facecolor('#111116')
    
    # Plot baseline state boundaries
    plt.plot(core_A.nodes[:, 0], core_A.nodes[:, 1], 'm-', alpha=0.4, label='Anchor Core A Path')
    plt.plot(initial_nodes_B[:, 0], initial_nodes_B[:, 1], 'c--', alpha=0.3, label='Core B Initial Boundary')
    
    # Plot evolved deformed loop shape
    plt.plot(core_B.nodes[:, 0], core_B.nodes[:, 1], color='cyan', linewidth=2.5, label='Core B Final Deformed Boundary')
    plt.scatter(core_B.nodes[:, 0], core_B.nodes[:, 1], color='cyan', s=20, zorder=3)
    
    # Plot statistical Center of Mass path migration
    plt.plot(com_B_track[:, 0], com_B_track[:, 1], color='yellow', linestyle=':', linewidth=2.0, label='Emergent COM Shift Path')
    plt.scatter(com_B_track[0, 0], com_B_track[0, 1], color='yellow', marker='*', s=120, label='COM Start', zorder=5)
    plt.scatter(com_B_track[-1, 0], com_B_track[-1, 1], color='cyan', marker='D', s=60, label='COM Current Location', zorder=5)
    
    plt.title("TIR Multi-Node Engine: Emergent Boundary Migration via Substrate Advection", color='white', fontsize=12)
    plt.xlabel("Substrate Plane: X", color='white')
    plt.ylabel("Substrate Plane: Y", color='white')
    plt.grid(color='#222233', linestyle=':', linewidth=0.5)
    ax.tick_params(colors='white')
    ax.set_aspect('equal')
    plt.legend(facecolor='#1c1c24', edgecolor='none', labelcolor='white')
    plt.show()