import numpy as np
import matplotlib.pyplot as plt

class VortexSystem:
    def __init__(self, name, position):
        self.name = name
        self.x = position
        
        # Bedrock Primitives (Isolated resting state)
        self.v_tan_core = 1.0   # Core tangential circulation velocity
        self.v_rad_core = 1.0   # Core radial pulse velocity amplitude
        self.a = 1.0            # Initial resting substrate impedance
        self.zeta = 1.0         # Coupling constant (1.0 = Upright Proton)
        
        # Self-solve initial core radius using the primitive equation
        self.r = (self.v_tan_core**2 + self.v_rad_core**2) / self.a

    def propagate_field_to_interface(self, r_interface):
        """
        Calculates how the core velocities decay as they propagate 
        outward through the medium to the 50/50 intersection point.
        Following standard scale-invariant wave field dissipation:
        """
        if r_interface <= 0:
            return self.v_tan_core, self.v_rad_core
            
        # Field attenuation profile relative to the core footprint
        scaling_factor = self.r / (r_interface + self.r)
        
        v_tan_at_interface = self.v_tan_core * scaling_factor
        v_rad_at_interface = self.v_rad_core * scaling_factor
        return v_tan_at_interface, v_rad_at_interface

# --- The Master System Loop Function ---
def run_interaction_solver(steps=400, proximity=0.45):
    # Step 1: Define primitive values for system_A, system_B, and system_AB
    system_A = VortexSystem("Proton_A", position=0.0)
    system_B = VortexSystem("Proton_B", position=proximity)
    
    # Tracking logs for plotting
    history = {"zeta": [], "a_impedance": [], "radius": [], "v_interaction": []}
    
    for step in range(steps):
        # Calculate spatial distance (system_AB)
        distance_AB = abs(system_B.x - system_A.x)
        
        # Step 2: Define values at the interface midpoint (r = r_system_AB / 2)
        r_interface = distance_AB / 2.0
        
        v_tan_A_int, v_rad_A_int = system_A.propagate_field_to_interface(r_interface)
        v_tan_B_int, v_rad_B_int = system_B.propagate_field_to_interface(r_interface)
        
        # Step 3: Intersection Solver (Add together at the intersection point)
        
        # A. First resolve velocity at the boundary interface using the vector interaction law
        # The coupling constant (zeta) acts as the projection modifier
        v_interaction_sq = (v_tan_A_int**2 + v_tan_B_int**2 + 
                            2.0 * (v_tan_A_int * v_tan_B_int) * system_B.zeta)
        v_interaction = np.sqrt(v_interaction_sq)
        
        # Resolve radial pulse collision impact
        # Upright clashing loops create massive head-on wave-front stagnation
        pulse_clash = (v_rad_A_int * v_rad_B_int) * system_B.zeta
        
        # Step 4: Output change in variables and take new "a" into system_AB
        # Structural stiffness 'a' spikes from the combined velocity and pulse clash
        a_new = 1.0 + (v_interaction_sq * 2.0) + (pulse_clash * 15.0)
        
        # B. Shift coupling constant (zeta) based on torque generated by the new substrate pressure
        # The system rolls away from the high-pressure clash toward the 90-degree neutron state (zeta -> 0)
        torque = pulse_clash * 0.12
        system_B.zeta = np.clip(system_B.zeta - torque, 0.0, 1.0)
        
        # C. Shift "r" according to the pure primitive equation constraint
        # The core radius is forced to dynamically scale based on the new localized acceleration environment
        system_B.v_rad_core = system_B.zeta # The radial pulse masks as it tilts
        system_B.a = a_new
        system_B.r = (system_B.v_tan_core**2 + system_B.v_rad_core**2) / system_B.a
        
        # Record state for analytical validation
        history["zeta"].append(system_B.zeta)
        history["a_impedance"].append(a_new)
        history["radius"].append(system_B.r)
        history["v_interaction"].append(v_interaction)
        
    return history

# --- Run the Simulation ---
sim_data = run_interaction_solver()

# --- Plotting the Emergent Evolution ---
fig, axs = plt.subplots(3, 1, figsize=(10, 8), sharex=True)

# Graph 1: The Phase Shift (Coupling Constant)
axs[0].plot(sim_data["zeta"], color='blue', linewidth=2.5, label='Coupling Constant ($\zeta$)')
axs[0].set_ylabel("Coupling ($\zeta$)", fontsize=11, fontweight='bold')
axs[0].set_title("3D Nucleon Field Solver: The Emergent Neutron Snap", fontsize=13, fontweight='bold', pad=15)
axs[0].grid(True, linestyle='--', alpha=0.5)
axs[0].legend(loc='upper right')

# Graph 2: Substrate Impedance Spike (a)
axs[1].plot(sim_data["a_impedance"], color='red', linewidth=2, label="Substrate Impedance ($a$)")
axs[1].set_ylabel("Pressure ($a$)", fontsize=11, fontweight='bold')
axs[1].grid(True, linestyle='--', alpha=0.5)
axs[1].legend(loc='upper right')

# Graph 3: Core Radius Adjustment (r)
axs[2].plot(sim_data["radius"], color='purple', linewidth=2, label="Core Radius ($r$)")
axs[2].set_ylabel("Core Radius ($r$)", fontsize=11, fontweight='bold')
axs[2].set_xlabel("Simulation Steps (Time)", fontsize=11, fontweight='bold')
axs[2].grid(True, linestyle='--', alpha=0.5)
axs[2].legend(loc='upper right')

plt.tight_layout()
plt.show()