import numpy as np
import matplotlib.pyplot as plt

class PureKinematicCore:
    def __init__(self, name, position, initial_velocity, core_radius=0.1):
        self.name = name
        self.x = position
        self.vx = initial_velocity
        
        # Primitives
        self.v_tan = 1.0
        self.v_rad = 1.0
        self.r = core_radius
        
    def get_edges(self, partner_x):
        """Locates the inner edge (facing partner) and outer edge (facing away)"""
        if self.x < partner_x:
            # Self is on the left, partner is on the right
            x_outer = self.x - self.r
            x_inner = self.x + self.r
        else:
            # Self is on the right, partner is on the left
            x_outer = self.x + self.r
            x_inner = self.x - self.r
        return x_outer, x_inner

def calculate_field_deficit(source_core, target_x, K=0.015):
    """
    Calculates the velocity potential deficit generated by a source core
    at a specific spatial coordinate target_x. Drops off with 1/R.
    """
    R = abs(target_x - source_core.x)
    # Prevent singularity division at absolute center
    R = max(0.02, R) 
    return K / R

def run_two_point_gravity_sim(steps=800, initial_separation=5.0):
    # Initialize particles at a distance with slight inward velocity
    core_A = PureKinematicCore("Core_A", position=0.0, initial_velocity=0.0005)
    core_B = PureKinematicCore("Core_B", position=initial_separation, initial_velocity=-0.0005)
    
    # Ambient unstructured vacuum velocity potential baseline (v0^2)
    P_ambient = 1.0
    
    history = {"distance": [], "P_outer_A": [], "P_inner_A": [], "radius_A": []}
    
    for step in range(steps):
        # 1. Track macroscopic separation
        distance = abs(core_B.x - core_A.x)
        
        # 2. Identify Boundary Edges
        x_out_A, x_in_A = core_A.get_edges(core_B.x)
        x_out_B, x_in_B = core_B.get_edges(core_A.x)
        
        # 3. Compute Pressures at Core A's Edges (Leeched by B's field)
        def_out_A = calculate_field_deficit(core_B, x_out_A)
        def_in_A = calculate_field_deficit(core_B, x_in_A)
        P_out_A = P_ambient - def_out_A
        P_in_A = P_ambient - def_in_A
        
        # 4. Compute Pressures at Core B's Edges (Leeched by A's field)
        def_out_B = calculate_field_deficit(core_A, x_out_B)
        def_in_B = calculate_field_deficit(core_A, x_in_B)
        P_out_B = P_ambient - def_out_B
        P_in_B = P_ambient - def_in_B
        
        # --- DYNAMIC DIRECTION FIX FOR STEP 5 ---
        # Find the real-time relative orientation of the two systems
        # Returns 1.0 if B is to the right of A, -1.0 if B is to the left of A
        direction_sign = np.sign(core_B.x - core_A.x)
        
        # Calculate the pure magnitude of the pressure push
        accel_A = (P_out_A - P_in_A) * 0.1
        accel_B = (P_out_B - P_in_B) * 0.1  
        
        # Apply the acceleration dynamically along the real-time interaction axis
        core_A.vx += accel_A * direction_sign
        core_B.vx -= accel_B * direction_sign
        
        core_A.x += core_A.vx
        core_B.x += core_B.vx
        
        # Directional mapping
        core_A.vx += accel_A  # Pushes right (positive)
        core_B.vx -= accel_B  # Pushes left (negative)
        
        core_A.x += core_A.vx
        core_B.x += core_B.vx
        

        # --- FIXING STEP 6 IN THE LOOP ---
        # Lock the internal core containment acceleration 'a' at baseline 1.0 
        # to preserve structural stability, preventing the inflation singularity.
        core_A.r = (core_A.v_tan**2 + core_A.v_rad**2) / 1.0
        core_B.r = (core_B.v_tan**2 + core_B.v_rad**2) / 1.0
        
        # Log data for dynamic verification
        history["distance"].append(distance)
        history["P_outer_A"].append(P_out_A)
        history["P_inner_A"].append(P_in_A)
        history["radius_A"].append(core_A.r)
        
    return history

# --- Execute Simulation and Render Performance Plots ---
sim_data = run_two_point_gravity_sim()
fig, axs = plt.subplots(3, 1, figsize=(10, 8), sharex=True)

# Graph 1: Dynamic Spatial Separation
axs[0].plot(sim_data["distance"], color='green', linewidth=2.5, label='Core-to-Core Separation ($R_{AB}$)')
axs[0].set_ylabel("Relational Distance", fontsize=11, fontweight='bold')
axs[0].set_title("Two-Point Boundary Pressure Solver (Pure Emergent Gravity)", fontsize=13, fontweight='bold', pad=15)
axs[0].grid(True, linestyle='--', alpha=0.5)
axs[0].legend()

# Graph 2: Edge Pressure Delta Verification
axs[1].plot(sim_data["P_outer_A"], color='blue', linewidth=2, label='Outer Edge Pressure ($P_{outer}$)')
axs[1].plot(sim_data["P_inner_A"], color='red', linestyle='--', linewidth=2, label='Inner Edge Pressure ($P_{inner}$)')
axs[1].set_ylabel("Velocity Potential ($v^2$)", fontsize=11, fontweight='bold')
axs[1].grid(True, linestyle='--', alpha=0.5)
axs[1].legend()

# Graph 3: Primitive Radius Resolution
axs[2].plot(sim_data["radius_A"], color='purple', linewidth=2, label='Core Radius ($r = v^2/a$)')
axs[2].set_ylabel("Core Radius ($r$)", fontsize=11, fontweight='bold')
axs[2].set_xlabel("Simulation Steps", fontsize=11, fontweight='bold')
axs[2].grid(True, linestyle='--', alpha=0.5)
axs[2].legend()

plt.tight_layout()
plt.show()