### Section VIII: Wave-Particle Duality & The Double-Slit Sieve

The wave-particle paradox of classical quantum mechanics is an artifact of treating empty space as an absolute void and particles as zero-dimensional abstract points. By replacing the abstract probability wavefunction with a physical, dual-zone loop structure interacting with an underlying photon-scale medium, the double-slit experiment resolves as a deterministic fluid-mechanical sorting machine.

---

## 1. The Anatomy of the Dual-Zone Structure

Under the Theory of Infinite Relativity (TIR), an elementary particle like an electron is never exclusively a wave or a particle. It is a permanent, localized dual-zone architecture:

* **The Core (The Particle Aspect):** A hyper-dense, high-torque central rotational stall where the tangential velocity has reached the medium's structural propagation threshold ($v_\theta \rightarrow c$).
* **The Field (The Wave Aspect):** A vast, low-torque outer boundary field ($r$) radiating outward across the underlying medium layer.

When an electron is fired at a macro-scale double-slit apparatus, the physical dimensions of the components dictate the interaction. The localized high-torque core is spatially constrained and can only pass through **one** slit. Concurrently, its extended low-torque outer field spans a wide enough spatial footprint to pass through **both** slits simultaneously.

As the outer field navigates the slits, it deforms the underlying medium, carving a localized hydrodynamic diffraction pattern of alternating high- and low-acceleration gradients ahead of the particle. The trailing core is then mechanically steered along the path of least resistance generated by its own leading field.

---

## 2. Wavelength as Geometric Helical Pitch

The classical de Broglie wavelength ($\lambda$) is stripped of its probabilistic interpretation and redefined as a literal spatial metric: **the Helical Pitch ($\lambda_{\text{geom}}$)**.

As a free loop propagates through space, its total velocity vector splits orthogonally between its internal tangential spin ($v_\theta = c$) and its forward radial propagation velocity ($v_r$):

$$v^2 = c^2 + v_r^2$$

The spatial wavelength is the precise forward radial distance the particle travels during one complete internal orbital period ($T = 2\pi r^{3/2}$):

$$\lambda_{\text{geom}} = v_r \cdot T = 2\pi v_r r^{3/2}$$

Because the particle's internal clock is fixed by its core geometric mass ($r = M_{\text{geom}}/c^2$), the trajectory of a moving electron through time traces a literal physical helix in the medium. Pumping energy into the particle alters its forward velocity ($v_r$), which compresses or elongates the physical pitch of this geometric spring.

---

## 3. Dimensional Translation of Laboratory Energy

To validate TIR against real-world data, laboratory energy measured in Electron-Volts ($\text{eV}$) must be converted into the medium's native dimensional profile ($\text{meters}^5 / \text{seconds}^4$). This is achieved via the universal scaling constant $\kappa$, which incorporates the gravitational constant ($G \equiv 1$) as a dimensional bridge:

$$\kappa = G \cdot (1.602 \times 10^{-19} \text{ Joules/eV}) \approx 1.069 \times 10^{-29} \text{ m}^5\text{s}^{-4}/\text{eV}$$

The kinetic energy ($K_{\text{geom}}$) injected to fire the electron forward belongs exclusively to the radial velocity component:

$$K_{\text{geom}} = \kappa \cdot E_{\text{eV}} = \frac{1}{2} M_{\text{geom}} v_r^2$$

Isolating the forward radial velocity yields:

$$v_r = \sqrt{\frac{2 \kappa E_{\text{eV}}}{M_{\text{geom}}}}$$

Substituting $v_r$ and the structural equilibrium radius ($r^{3/2} = M_{\text{geom}}^{3/2}/c^3$) back into the wavelength equations yields the definitive **TIR Helical Pitch Formula**:

$$\lambda_{\text{geom}} = \frac{2\pi \sqrt{2 \kappa E_{\text{eV}} M_{\text{geom}}}}{c^3}$$

Plugging this directly into the classical slit intensity equation maps the exact spatial distribution of the particle hits on a detector screen at an angle $\theta$:

$$I(\theta) \propto \cos^2\left(\frac{c^3 d \sin\theta}{2 \sqrt{2 \kappa E_{\text{eV}} M_{\text{geom}}}}\right)$$

The $\cos^2$ function operates as a fluid-mechanical efficiency rating. Fringes are not probabilities; they are regions where the structural propagation threshold of the medium ($c^3$) either funnels the helical spring smoothly forward ($\cos^2 \rightarrow 1$) or generates catastrophic frictional resistance ($\cos^2 \rightarrow 0$), mechanically deflecting the core away from the coordinate.

---

## 4. The Screen Interface: Boundary Resolution Dynamics

When the electron arrives at the detection screen—which consists of a highly tensioned lattice of nested atomic loops—the manifestation of a discrete "particle hit" is governed by an all-or-nothing digital threshold. Whether a localized state change occurs depends on the **Velocity Ratio ($\frac{v_\theta}{v_r}$)**, which represents the alignment of the incoming helix relative to the orbital transit time of the target atom.

The interaction splits into three strictly deterministic, scale-invariant mechanical outcomes:

### I. Sub-Threshold Core Penetration & Volumetric Shear (The Photon Emission)

When the scalar velocity ratio falls below the critical interaction threshold ($\frac{v_\theta}{v_r} < \text{Threshold}$), the forward radial velocity is too high relative to the loop's internal orbital spin. The spatial pitch of the incoming helix is too wide to satisfy the phase-matching condition within the outer harmonic shell; the loop transits the orbital domain without intersecting the bound electron's path.

Consequently, the incoming loop penetrates directly into the steep acceleration gradient ($a$) of the hyper-dense core, where $a = M_{\text{geom}}/r^2$ spikes exponentially as $r \rightarrow 10^{-15}\text{ m}$. Because total velocity is bounded ($v^2 = v_\theta^2 + v_r^2$), the loop cannot maintain its structural equilibrium equation ($r = v^2/a$) against this colossal gradient while retaining forward momentum. This forces an immediate velocity saturation lock, driving the forward radial component abruptly to zero ($v_r \rightarrow 0$).

Because the incoming loop scale lacks a resonant harmonic match with the hyper-dense core's deep sub-quantum gear layer, this sudden step-discontinuity in radial velocity ($\frac{dv_r}{dt} \rightarrow \infty$) cannot be absorbed as localized internal torque. The unabsorbed deceleration energy causes an abrupt volumetric shear deformation in the underlying medium. This localized displacement is shed outward as a transient wave excitation—a literal mechanical pluck propagating natively across the photon-scale surface layer at the boundary threshold velocity ($c$), which is macroscopically detected as a **Photon Emission**.

### II. Integer Harmonic Phase-Lock & Geometric Torque Transfer (Ionization)

When the velocity ratio exceeds the baseline threshold and matches an integer harmonic ($\frac{v_\theta}{v_r} = n$), an intersection with the target atom's outer orbital shell becomes a mechanical certainty.

If the relative algebraic sign of their tangential velocities matches ($\Delta v_\theta = v_{\text{bound}} - v_{\text{incoming}} \rightarrow 0$), the teeth of the two independent fields drop into perfect phase-alignment. The fields lock instantly. The incoming loop's forward velocity drops to zero ($v_r \rightarrow 0$), and its remaining energy forces an immediate, violent spike in the tangential spin component ($v_\theta$), dumping its cumulative geometric torque ($M_{\text{geom}}$) directly into the bound orbital loop.

This sudden torque overload destabilizes the target loop's equilibrium ($r = v^2/a$), causing it to un-moor and spin out of the atom's field entirely. The incoming loop is deflected away with depleted energy, leaving the parent atom with a permanent structural vacancy—observed macroscopically as **Ionization**.

### III. Non-Resonant Phase Mismatch & Frictional Deflection (Elastic Scattering)

If the velocity ratio exceeds the threshold but forms an irrational or counter-rotating fractional relationship ($\Delta v_\theta \rightarrow 2v$), the fields interface out of phase. The fields collide out of alignment, creating localized sub-quantum friction. A clean phase-lock cannot establish. The fields mechanically buffet and deflect off one another without triggering a structural state change, manifesting macroscopically as **Elastic Scattering** or background **Quantum Jitter**.